### ISSUE TITLE
Timer limited to 999s

### ISSUE THREAD

**Issue by ayoungethan** [mfep/exercise-timer#11]
I try to enter a session of 25min (1500sec), and timer automatically sets to 999sec (16:39).

Timer would be much more useful if longer sessions could be started as well. It can be used not just for workouts but eg more like a Pomodoro timer.

**Comment by mfep** [comment]
Nice catch, the limit is arbitrary. Also, I like the suggestion about making this utility to a general purpose interval timer.

The limit should be fixed in https://github.com/mfep/exercise-timer/commit/4f128b75cf7904ab1fd02e496d5e00ec44a08804. I'll push an update to Flathub soon.
